spring.application.name=TarotPokerApplication

security.jwt.secret=tarot-poker-jwt-secret-key-for-hmac-sha256-algorithm-very-secure-2024-lab5
security.jwt.expiration-ms=86400000

spring.datasource.url=jdbc:h2:mem:tarotdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=adm
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

telegram.bot.token=${BOT_TOKEN}
telegram.bot.username=@TarotPokerGamebot

logging.level.org.telegram=DEBUG
logging.level.org.apache.http=DEBUG

